-- © 2024–2026 Lila Alexandra Olufemi Inglis Abegunrin. All Rights Reserved. FlatFinder™
-- Migration: 004 — add_foreign_key_indexes
-- Generated by FlatFinder™ Database Architect Agent
-- Date: 2026-04-16T12:01:15.306342+00:00

-- Add indexes for foreign key columns to improve query performance

-- Agent Violations foreign key index
CREATE INDEX IF NOT EXISTS idx_agent_violations_agent_id 
ON agent_violations(agent_id);

-- Listings foreign key indexes
CREATE INDEX IF NOT EXISTS idx_listings_agent_id 
ON listings(agent_id);

-- Agent Reports foreign key indexes
CREATE INDEX IF NOT EXISTS idx_agent_reports_agent_id 
ON agent_reports(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_reports_user_id 
ON agent_reports(user_id);

-- Renter Demands foreign key indexes
CREATE INDEX IF NOT EXISTS idx_renter_demands_user_id 
ON renter_demands(user_id);
CREATE INDEX IF NOT EXISTS idx_renter_demands_listing_id 
ON renter_demands(listing_id);
CREATE INDEX IF NOT EXISTS idx_renter_demands_agent_id 
ON renter_demands(agent_id);

-- Saved Searches foreign key index
CREATE INDEX IF NOT EXISTS idx_saved_searches_user_id 
ON saved_searches(user_id);

-- Search Blitz Orders foreign key index
CREATE INDEX IF NOT EXISTS idx_search_blitz_orders_user_id 
ON search_blitz_orders(user_id);