-- © 2024–2026 Lila Alexandra Olufemi Inglis Abegunrin. All Rights Reserved. FlatFinder™
-- Migration: 003 — Row Level Security Policies
-- Generated by FlatFinder™ Database Architect Agent
-- Fixes: All 8 tables were missing RLS ENABLE and policies

-- ─────────────────────────────────────────────────────────────────────────────
-- ENABLE RLS ON ALL TABLES
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE agents             ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_violations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE listings           ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_reports      ENABLE ROW LEVEL SECURITY;
ALTER TABLE renter_demands     ENABLE ROW LEVEL SECURITY;
ALTER TABLE demand_templates   ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_searches     ENABLE ROW LEVEL SECURITY;
ALTER TABLE search_blitz_orders ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- AGENTS — public read, service-role write
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY "agents_public_read"
  ON agents FOR SELECT
  USING (true);

CREATE POLICY "agents_service_write"
  ON agents FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────────────
-- AGENT VIOLATIONS — public read, service-role write
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY "agent_violations_public_read"
  ON agent_violations FOR SELECT
  USING (true);

CREATE POLICY "agent_violations_service_write"
  ON agent_violations FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────────────
-- LISTINGS — public read of active listings, service-role write
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY "listings_public_read_active"
  ON listings FOR SELECT
  USING (is_active = true AND is_scam = false);

CREATE POLICY "listings_service_write"
  ON listings FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────────────
-- AGENT REPORTS — users can insert their own, read their own; service reads all
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY "agent_reports_user_insert"
  ON agent_reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "agent_reports_user_read_own"
  ON agent_reports FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "agent_reports_service_all"
  ON agent_reports FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────────────
-- RENTER DEMANDS — fully private, user owns their own rows
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY "renter_demands_user_own"
  ON renter_demands FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "renter_demands_service_all"
  ON renter_demands FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────────────
-- DEMAND TEMPLATES — public read (used by all tenants)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY "demand_templates_public_read"
  ON demand_templates FOR SELECT
  USING (is_active = true);

CREATE POLICY "demand_templates_service_write"
  ON demand_templates FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────────────
-- SAVED SEARCHES — user owns their own rows
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY "saved_searches_user_own"
  ON saved_searches FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "saved_searches_service_all"
  ON saved_searches FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ─────────────────────────────────────────────────────────────────────────────
-- SEARCH BLITZ ORDERS — user owns their own rows
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY "search_blitz_orders_user_own"
  ON search_blitz_orders FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "search_blitz_orders_service_all"
  ON search_blitz_orders FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');
